version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017